### PR TITLE
add support for scoped npm packages

### PR DESCRIPTION
**Pull request by pwmckenna**
addresses https://github.com/yahoo/locator/issues/34

to test I just moved one of the node_modules into a scope folder.

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by redonkulus** [comment]
@drewfish to review

**Comment by drewfish** [comment]
LGTM

@pwmckenna could you sign the CLA? Once that's done I can merge and release a new version.

**Comment by pwmckenna** [comment]
@drewfish I signed it immediately after I created the PR, but the check didn't seem to update when I did it. I'll change then unchange some whitespace. Hopefully it'll respond to a fresh push.

**Comment by pwmckenna** [comment]
ah, looks like that did the trick.

**Comment by drewfish** [comment]
Published as locator@1.3.0. Thanks!

**Pull request merged**
